### ISSUE TITLE
Support for C.H.I.P. Debian 4.4

### ISSUE THREAD

**Issue by stanelie** [hadess/CHIP-bluetooth-speaker#16]
It looks like it's not working on my headless 4.4, I reverted to 4.3 and it works there.

**Comment by mohsen3** [comment]
It works fine with 4.4 GUI version!

**Comment by hadess** [comment]
Works fine with the 4.4.13-ntc-mlc kernel that's installed with the current 4.4 headless version. Try to reflash your CHIP and update it before testing the script out again.

If you still have a problem, please file a new issue with _some_ details about what's not working because there's really nothing to go on in this report.
