### ISSUE TITLE
AirPlay support

### ISSUE THREAD

**Issue by hadess** [hadess/CHIP-bluetooth-speaker#7]
This would likely use shairport, but we'd need some integration with PulseAudio to make sure that only one audio is playing at a time.

**Comment by chadberg** [comment]
I did this with Shairport, and because I'm using it portably, also added a script to automatically connect to open networks. Good thing I don't keep any sensitive information on the CHIP! But I didn't do anything with pulse to make sure only one stream at a time is playing.... I just only connect one source at a time.

It's a good feature, and I'd like to see it in there. Shairport-sync allows you to stream to multiple CHIPs at once and keep things in sync. Like a low cost version of SONOS.

**Comment by hadess** [comment]
From https://github.com/mikebrady/shairport-sync/issues/420#issuecomment-260202123
> Hmm. A couple of things. Shairport Sync is not compatible with PulseAudio (PA).

So not going to happen.
